//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class element
    {
        public int i { get; set; }
        public Nullable<int> P0 { get; set; }
        public Nullable<int> P1 { get; set; }
        public Nullable<int> P2 { get; set; }
        public Nullable<int> P3 { get; set; }
        public Nullable<int> P4 { get; set; }
        public Nullable<int> P5 { get; set; }
        public Nullable<int> P6 { get; set; }
        public Nullable<int> P7 { get; set; }
    }
}
